openapi: 3.0.0
info:
  title: Admin Order API
  version: 1.0.0
  description: API for managing orders by admin

paths:
  /admin/orders:
    get:
      summary: Get all orders
      tags:
        - Admin Orders
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of all orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '403':
          description: Access denied (not admin)
        '500':
          description: Internal server error

  /admin/orders/{id}:
    put:
      summary: Update order status by ID
      tags:
        - Admin Orders
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  example: Delivered
      responses:
        '200':
          description: Order updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Order not found
        '500':
          description: Internal server error

    delete:
      summary: Delete an order by ID
      tags:
        - Admin Orders
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order deleted successfully
        '404':
          description: Order not found
        '500':
          description: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Order:
      type: object
      properties:
        _id:
          type: string
        user:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
        status:
          type: string
        isDelivered:
          type: boolean
        deliveredAt:
          type: string
          format: date-time
