openapi: 3.0.0
info:
  title: Admin Product API
  version: 1.0.0
  description: API for managing products by admin

paths:
  /admin/products:
    get:
      summary: Get all products
      tags:
        - Admin Products
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of all products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '403':
          description: Access denied (not admin)
    post:
      summary: Create a new product
      tags:
        - Admin Products
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Bad request
        '403':
          description: Access denied (not admin)

  /admin/products/{id}:
    get:
      summary: Get a product by ID (currently calls updateProduct in your route)
      tags:
        - Admin Products
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
        '403':
          description: Access denied (not admin)

    delete:
      summary: Delete a product by ID
      tags:
        - Admin Products
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product deleted successfully
        '404':
          description: Product not found
        '403':
          description: Access denied (not admin)

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        price:
          type: number
        description:
          type: string
        category:
          type: string
        stock:
          type: integer
        image:
          type: string
