openapi: 3.0.0
info:
  title: Cart API
  version: 1.0.0
  description: API for managing shopping cart (add, update quantity, remove, view, merge guest cart)
servers:
  - url: http://localhost:3000/api/cart
paths:
  /:
    post:
      summary: Add product to cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                quantity:
                  type: integer
                storage:
                  type: string
                color:
                  type: string
                ram:
                  type: string
                guestId:
                  type: string
                userId:
                  type: string
              required:
                - productId
                - quantity
      responses:
        '201':
          description: Product added to cart
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '404':
          description: Product not found
        '500':
          description: Server error

    put:
      summary: Update product quantity in cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                quantity:
                  type: integer
                storage:
                  type: string
                color:
                  type: string
                ram:
                  type: string
                guestId:
                  type: string
                userId:
                  type: string
              required:
                - productId
                - quantity
      responses:
        '200':
          description: Cart updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '404':
          description: Cart or product not found
        '500':
          description: Server error

    delete:
      summary: Remove product from cart
      parameters:
        - in: query
          name: productId
          required: true
          schema:
            type: string
          description: ID of the product to remove
        - in: query
          name: storage
          schema:
            type: string
          description: Storage variant of the product
        - in: query
          name: color
          schema:
            type: string
          description: Color variant of the product
        - in: query
          name: ram
          schema:
            type: string
          description: RAM variant of the product
        - in: query
          name: guestId
          schema:
            type: string
          description: Guest user ID
        - in: query
          name: userId
          schema:
            type: string
          description: Authenticated user ID
      responses:
        '200':
          description: Product removed from cart
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '404':
          description: Cart or product not found
        '500':
          description: Server error

    get:
      summary: Get cart for user or guest
      parameters:
        - in: query
          name: userId
          schema:
            type: string
          description: Authenticated user ID
        - in: query
          name: guestId
          schema:
            type: string
          description: Guest user ID
      responses:
        '200':
          description: Cart retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '404':
          description: Cart not found
        '500':
          description: Server error

  /merge:
    post:
      summary: Merge guest cart into authenticated user's cart
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                guestId:
                  type: string
              required:
                - guestId
      responses:
        '200':
          description: Cart merged successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '404':
          description: Guest cart not found or empty
        '500':
          description: Server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    CartItem:
      type: object
      properties:
        productId:
          type: string
        name:
          type: string
        image:
          type: string
        price:
          type: number
          format: float
        color:
          type: string
        ram:
          type: string
        storage:
          type: string
        quantity:
          type: integer

    Cart:
      type: object
      properties:
        _id:
          type: string
        user:
          type: string
          nullable: true
        guestId:
          type: string
          nullable: true
        products:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
        totalPrice:
          type: number
          format: float
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
