openapi: 3.0.0
info:
  title: Checkout API
  version: 1.0.0
paths:
  /api/checkout:
    post:
      summary: Create checkout
      tags:
        - Checkout
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                checkoutItems:
                  type: array
                  items:
                    type: object
                shippingAddress:
                  type: object
                paymentMethod:
                  type: string
                totalPrice:
                  type: number
      responses:
        '201':
          description: Checkout created successfully
  /api/checkout/{id}/pay:
    put:
      summary: Update checkout payment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Checkout updated successfully
  /api/checkout/{id}/finalize:
    post:
      summary: Finalize the checkout
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Checkout finalized successfully
