openapi: 3.0.0
info:
  title: Order API
  version: 1.0.0
  description: API for retrieving customer orders

servers:
  - url: http://localhost:5000/api

paths:
  /orders/my-orders:
    get:
      tags:
        - Orders
      summary: Get orders of the logged-in customer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successfully fetched orders
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Orders fetched successfully
                  orders:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
        '401':
          description: Unauthorized

  /orders/{id}:
    get:
      tags:
        - Orders
      summary: Get order details by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: 662f08a331b207f9ccf23d33
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successfully fetched order details
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Order details fetched successfully
                  order:
                    $ref: '#/components/schemas/Order'
        '404':
          description: Order not found
        '401':
          description: Unauthorized

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    OrderItem:
      type: object
      properties:
        productId:
          type: string
        name:
          type: string
        image:
          type: string
        price:
          type: number
        color:
          type: string
        ram:
          type: string
        storage:
          type: string
        quantity:
          type: number

    Order:
      type: object
      properties:
        _id:
          type: string
        user:
          type: object
          properties:
            _id:
              type: string
            name:
              type: string
            email:
              type: string
        orderItems:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        shippingAddress:
          type: object
          properties:
            address:
              type: string
            city:
              type: string
            postalCode:
              type: string
            country:
              type: string
        paymentMethod:
          type: string
        totalPrice:
          type: number
        isPaid:
          type: boolean
        paidAt:
          type: string
          format: date-time
        isDelivered:
          type: boolean
        deliveredAt:
          type: string
          format: date-time
        paymentStatus:
          type: string
        status:
          type: string
          enum: [Processing, Shipped, Delivered, Cancelled]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
