openapi: 3.0.0
info:
  title: E-Commerce API
  version: 1.0.0
  description: API documentation for the e-commerce platform.
servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  /upload:
    post:
      summary: Upload an image to Cloudinary
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Image uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  imageUrl:
                    type: string
                  public_id:
                    type: string
        '400':
          description: No file uploaded
        '500':
          description: Internal server error

  /subscribe:
    post:
      summary: Subscribe a user via email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '201':
          description: Subscription successful
        '400':
          description: Invalid email or already subscribed
        '500':
          description: Internal server error

  /products:
    get:
      summary: Retrieve all products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Server error

    post:
      summary: Create a new product
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '201':
          description: Product created successfully
        '400':
          description: Invalid input
        '500':
          description: Server error

  /products/filtered:
    get:
      summary: Retrieve filtered products
      parameters:
        - in: query
          name: storage
          schema:
            type: string
        - in: query
          name: color
          schema:
            type: string
        - in: query
          name: ram
          schema:
            type: string
        - in: query
          name: minPrice
          schema:
            type: number
        - in: query
          name: maxPrice
          schema:
            type: number
        - in: query
          name: sortBy
          schema:
            type: string
        - in: query
          name: search
          schema:
            type: string
        - in: query
          name: category
          schema:
            type: string
        - in: query
          name: brand
          schema:
            type: string
        - in: query
          name: limit
          schema:
            type: integer
      responses:
        '200':
          description: Filtered products retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
        '500':
          description: Server error

  /products/similar/{id}:
    get:
      summary: Retrieve similar products
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Similar products retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
        '500':
          description: Server error

  /products/best-seller:
    get:
      summary: Retrieve best seller products
      responses:
        '200':
          description: Best seller products retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Product'
        '404':
          description: No best seller products found
        '500':
          description: Server error

  /products/new-arrivals:
    get:
      summary: Retrieve new arrivals products
      responses:
        '200':
          description: New arrivals products retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
        '404':
          description: No new arrivals products found
        '500':
          description: Server error

  /products/{id}:
    get:
      summary: Retrieve a product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
        '500':
          description: Server error

    put:
      summary: Update a product by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '200':
          description: Product updated successfully
        '404':
          description: Product not found
        '500':
          description: Server error

    delete:
      summary: Delete a product by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product removed
        '404':
          description: Product not found
        '500':
          description: Server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
        discountPrice:
          type: number
        countInStock:
          type: integer
        sku:
          type: string
        category:
          type: string
        brand:
          type: string
        colors:
          type: array
          items:
            type: string
        ram:
          type: array
          items:
            type: string
        storage:
          type: array
          items:
            type: string
        images:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
              altText:
                type: string
        isFeatured:
          type: boolean
        isPublished:
          type: boolean
        rating:
          type: number
        numReviews:
          type: integer
        tags:
          type: array
          items:
            type: string
        user:
          type: string
        metaTitle:
          type: string
        metaDescription:
          type: string
        metaKeywords:
          type: array
          items:
            type: string
        dimensions:
          type: object
          properties:
            length:
              type: number
            width:
              type: number
            height:
              type: number
        weight:
          type: number
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ProductInput:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        price:
          type: number
        discountPrice:
          type: number
        countInStock:
          type: integer
        sku:
          type: string
        category:
          type: string
        brand:
          type: string
        colors:
          type: array
          items:
            type: string
        ram:
          type: array
          items:
            type: string
        storage:
          type: array
          items:
            type: string
        images:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
              altText:
                type: string
        isFeatured:
          type: boolean
        isPublished:
          type: boolean
        tags:
          type: array
          items:
            type: string
        metaTitle:
          type: string
        metaDescription:
          type: string
        metaKeywords:
          type: array
          items:
            type: string
        dimensions:
          type: object
          properties:
            length:
              type: number
            width:
              type: number
            height:
              type: number
        weight:
          type: number
