openapi: 3.0.3
info:
  title: Subscriber API
  version: 1.0.0
  description: API for subscribing users via email.

servers:
  - url: http://localhost:5000/api/subscriber
    description: Local development server

paths:
  /subscribe:
    post:
      summary: Subscribe a user via email
      description: Adds a user to the email subscription list.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
      responses:
        '201':
          description: Subscription successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Subscription successful
        '400':
          description: Invalid or duplicate email
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Email already subscribed
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error
