openapi: 3.0.3
info:
  title: Image Upload API
  version: 1.0.0
  description: Upload an image to Cloudinary using multer and streamifier.

servers:
  - url: http://localhost:5000/api/upload
    description: Local development server

paths:
  /:
    post:
      summary: Upload an image
      description: Uploads a single image file to Cloudinary and returns the image URL and public ID.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - image
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: File uploaded successfully
                  imageUrl:
                    type: string
                    example: https://res.cloudinary.com/demo/image/upload/v1234567890/sample.jpg
                  public_id:
                    type: string
                    example: sample_public_id
        '400':
          description: No file uploaded
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: No file uploaded
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error
